### ISSUE TITLE
Token muy corto

### ISSUE THREAD

**Issue by cybercamphackathon** [zevenet/SmartDDoSFilter#10]
https://github.com/zevenet/SmartDDoSFilter/blob/661a19cc3c5583d495cc22cdce9d82c873939cd7/nftlb/src/server.c#L39

16 caracteres es muy corto para un token. Yo lo haría mucho más largo, por ejemplo 128 caracteres.

**Comment by nevola** [comment]
Se puede modificar fácilmente, hay que tener en cuenta también que no está expuesto al exterior sólamente a la red interna.

**Comment by nevola** [comment]
Añadida key más larga y solucionado bug detectado gracias a este cambio :)
7a8c2a966dda1bec61b2e0340fecbd352b2e6195
