### ISSUE TITLE
Memory Leak y Off-by-One

### ISSUE THREAD

**Issue by cybercamphackathon** [zevenet/SmartDDoSFilter#11]
https://github.com/zevenet/SmartDDoSFilter/blob/661a19cc3c5583d495cc22cdce9d82c873939cd7/nftlb/src/server.c#L496

Al usar ++i en el bucle, el contenido del bucle irá de la posición 1 a la posición SRV_KEY_LENGTH (inclusive). Esto tiene dos consecuencias:

1. El primer byte de la clave va a mostrar un byte de la memoria no inicializada.
2. Se sobreescribirá 1 byte de memoria continua al buffer, lo que vulgarmente se conoce como "off-by-one".

Creo que deberiais cambiarlo por i++

**Comment by nevola** [comment]
Arreglado en e07e8dfa582b24b573d502d088247c2b6c229a10
