### ISSUE TITLE
La regla de nftables para RST no detecta la flag

### ISSUE THREAD

**Issue by alvarocano-zevenet** [zevenet/SmartDDoSFilter#12]
La regla de nftables que hace el match contra la flag de TCP no funciona correctamente.

**Comment by nevola** [comment]
@alvarocano-zevenet prueba con tcp flags & rst ó tcp flags & rst == rst

**Comment by alvarocano-zevenet** [comment]
Parece que el error viene del match en nft

**Comment by nevola** [comment]
Hay que actualizar nftables para solucionarlo
