### ISSUE TITLE
IP harcodeada en el código

### ISSUE THREAD

**Issue by cybercamphackathon** [zevenet/SmartDDoSFilter#5]
https://github.com/zevenet/SmartDDoSFilter/blob/5d928364d537076e04575a9a89b68c9d7780bd5b/wrk/src/wrk.c#L255

¿Este código forma parte de vuestro proyecto? A no ser que sea un parche rápido para usarlo para pruebas, os recomendaría que sacarais estas IPs como parámetro.

**Comment by luisvalencia-zevenet** [comment]
Gracias por la indicación. Ya contemplamos esta problemática y hay que tener en cuenta que el parche surgió de una necesidad urgente para pruebas.
Sin embargo es algo provisional sobre lo que estamos trabajando. En las próximas horas liberaremos un parche para hacer uso de fichero de configuración, solventando esto mismo.
Un saludo.

**Comment by luisvalencia-zevenet** [comment]
Subido commit 0a7451c6aed5f77a97d478a26657c02bdb1bab6a que soluciona este issue, procedo al cierre.
