### ISSUE TITLE
Posible condición de carrera

### ISSUE THREAD

**Issue by cybercamphackathon** [zevenet/SmartDDoSFilter#8]
https://github.com/zevenet/SmartDDoSFilter/blob/661a19cc3c5583d495cc22cdce9d82c873939cd7/nftlb/src/policies.c

Lo mismo que en la issue #7

**Comment by luisvalencia-zevenet** [comment]
¡Hola! Marco como duplicada el issue y procedo a unir los dos issues relacionados.

**Comment by cybercamphackathon** [comment]
Me parece correcto.
