### ISSUE TITLE
Semilla no aleatoria

### ISSUE THREAD

**Issue by cybercamphackathon** [zevenet/SmartDDoSFilter#9]
https://github.com/zevenet/SmartDDoSFilter/blob/661a19cc3c5583d495cc22cdce9d82c873939cd7/nftlb/src/server.c#L495

La hora en la que arrancó el servicio es relativamente predecible, y el PID del proceso es un espacio de valores bastante pequeño (ya fue un problema en aquel bug del PRNG de Debian de hace unos años). La semilla debería inicializarse a un valor "true random".

**Comment by nevola** [comment]
Lo miramos, aunque hay que tener en cuenta que el servicio es sólo para gestión remota y no está expuesto al exterior.

**Comment by cybercamphackathon** [comment]
Como estais usando un tunel SSH, la clave SSH que useis sirve como workaround.
Poned que teneis que cambiar eso en el TODO y podeis cerrar la issue.

**Comment by luisvalencia-zevenet** [comment]
Hemos actualizado el TODO, muchas gracias.

**Comment by luisvalencia-zevenet** [comment]
Procedemos al cierre tras la actualización del fichero TODO.

https://github.com/zevenet/SmartDDoSFilter/blob/master/TODO
